export const API_ENDPOINTS = {
  health: {
    root: "/api/health/",
    live: "/api/health/live/",
    ready: "/api/health/ready/",
    deps: "/api/health/deps/",
  },
  docs: {
    schema: "/api/schema/",
    swagger: "/api/docs/",
  },
  accounts: {
    register: "/api/accounts/register/",
    activate: "/api/accounts/activate/",
    resendActivationOtp: "/api/accounts/resend-activation-otp/",
    login: "/api/accounts/login/",
    me: "/api/accounts/me/",
    passwordResetRequest: "/api/accounts/password-reset/request/",
    passwordResetConfirm: "/api/accounts/password-reset/confirm/",
    tokenRefresh: "/api/accounts/token/refresh/",
    logout: "/api/accounts/logout/",
  },
  profiles: {
    me: "/api/profiles/me/",
    userProfile: "/api/profiles/me/user-profile/",
    patient: "/api/profiles/me/patient/",
    doctor: "/api/profiles/me/doctor/",
    pharmacist: "/api/profiles/me/pharmacist/",
    laboratorian: "/api/profiles/me/laboratorian/",
  },
  consultations: {
    create: "/api/consultations/",
    my: "/api/consultations/my/",
    doctorPending: "/api/consultations/doctor/pending/",
    doctorAssigned: "/api/consultations/doctor/assigned/",
    detail: (id: string) => `/api/consultations/${id}/`,
    accept: (id: string) => `/api/consultations/${id}/accept/`,
    close: (id: string) => `/api/consultations/${id}/close/`,
    responses: (id: string) => `/api/consultations/${id}/responses/`,
    messages: (id: string) => `/api/consultations/${id}/messages/`,
    markMessagesRead: (id: string) => `/api/consultations/${id}/messages/mark-read/`,
    symptomCategories: "/api/consultations/symptom-categories/",
    symptoms: "/api/consultations/symptoms/",
  },
  prescriptions: {
    my: "/api/prescriptions/my/",
    myDetail: (id: string) => `/api/prescriptions/my/${id}/`,
    byDoctor: (id: string) => `/api/prescriptions/doctor/${id}/`,
    cancelByDoctor: (id: string) => `/api/prescriptions/doctor/${id}/cancel/`,
    createForConsultation: (consultationId: string) => `/api/consultations/${consultationId}/prescriptions/`,
    scan: "/api/prescriptions/scan/",
    dispense: (id: string) => `/api/prescriptions/${id}/dispense/`,
  },
  labOrders: {
    tests: "/api/lab-orders/tests/",
    my: "/api/lab-orders/my/",
    myDetail: (id: string) => `/api/lab-orders/my/${id}/`,
    byDoctor: (id: string) => `/api/lab-orders/doctor/${id}/`,
    cancelByDoctor: (id: string) => `/api/lab-orders/doctor/${id}/cancel/`,
    createForConsultation: (consultationId: string) => `/api/consultations/${consultationId}/lab-orders/`,
    scan: "/api/lab-orders/scan/",
    complete: (id: string) => `/api/lab-orders/${id}/complete/`,
    resultDetail: (id: string) => `/api/lab-orders/results/${id}/`,
    doctorResultDetail: (id: string) => `/api/lab-orders/doctor/results/${id}/`,
    doctorResultReview: (id: string) => `/api/lab-orders/doctor/results/${id}/review/`,
    doctorResultRelease: (id: string) => `/api/lab-orders/doctor/results/${id}/release/`,
    doctorResultLinkMedicalRecord: (id: string) => `/api/lab-orders/doctor/results/${id}/link-medical-record/`,
    createItemResult: (itemId: string) => `/api/lab-orders/items/${itemId}/results/`,
    correctResult: (id: string) => `/api/lab-orders/results/${id}/correct/`,
  },
  labResults: {
    my: "/api/lab-results/my/",
    myDetail: (id: string) => `/api/lab-results/my/${id}/`,
    myFromLabOrders: "/api/lab-orders/my-results/",
    myDetailFromLabOrders: (id: string) => `/api/lab-orders/my-results/${id}/`,
  },
  patientRecords: {
    my: "/api/patient-records/my/",
    byPatient: (patientId: string) => `/api/patient-records/patients/${patientId}/`,
    createEntry: (recordId: string) => `/api/patient-records/${recordId}/entries/`,
    confirmEntry: (entryId: string) => `/api/patient-records/entries/${entryId}/confirm/`,
    deactivateEntry: (entryId: string) => `/api/patient-records/entries/${entryId}/deactivate/`,
    setBloodGroup: (recordId: string) => `/api/patient-records/${recordId}/blood-group/`,
    verifyBloodGroup: (patientId: string) => `/api/patient-records/patients/${patientId}/blood-group/verify/`,
  },
  notifications: {
    list: "/api/notifications/",
    unreadCount: "/api/notifications/unread-count/",
    markRead: (id: string) => `/api/notifications/${id}/mark-read/`,
    markAllRead: "/api/notifications/mark-all-read/",
  },
  knowledgeBase: {
    documents: "/api/knowledge-base/documents/",
    documentDetail: (id: string) => `/api/knowledge-base/documents/${id}/`,
    process: (id: string) => `/api/knowledge-base/documents/${id}/process/`,
    approve: (id: string) => `/api/knowledge-base/documents/${id}/approve/`,
    reject: (id: string) => `/api/knowledge-base/documents/${id}/reject/`,
    archive: (id: string) => `/api/knowledge-base/documents/${id}/archive/`,
    embed: (id: string) => `/api/knowledge-base/documents/${id}/embed/`,
    chunksByDocument: (id: string) => `/api/knowledge-base/documents/${id}/chunks/`,
    chunksSearch: "/api/knowledge-base/chunks/search/",
    chunksSemanticSearch: "/api/knowledge-base/chunks/semantic-search/",
  },
  rag: {
    doctorQuery: "/api/rag/doctor/query/",
    consultationSupport: (id: string) => `/api/rag/consultations/${id}/support/`,
    labResultSupport: (id: string) => `/api/rag/lab-results/${id}/support/`,
    feedbackCreate: (id: string) => `/api/rag/responses/${id}/feedback/`,
    myFeedback: "/api/rag/feedback/my/",
    adminFeedback: "/api/rag/admin/feedback/",
    adminReviewFeedback: (id: string) => `/api/rag/admin/feedback/${id}/review/`,
    adminAnalyticsSummary: "/api/rag/admin/analytics/summary/",
    adminExportDataset: "/api/rag/admin/exports/dataset/",
  },
  websocket: {
    user: "/ws/user/",
    consultationMessages: (consultationId: string) => `/ws/consultations/${consultationId}/messages/`,
  },
} as const;

export type ApiEndpoints = typeof API_ENDPOINTS;
