export type DocLocalizedTerm = {
  ar: string;
  ku: string;
};

export const DOC_EXACT_MEDICAL_TERMS: Record<string, DocLocalizedTerm> = {
  "Abdominal pain": { ar: "ألم البطن", ku: "ئازاری سک" },
  "Abnormal vaginal bleeding": { ar: "نزيف مهبلي غير طبيعي", ku: "خوێنبەربوونی نا ئاسایی لە زێ" },
  "Allergy / Immunology": { ar: "الحساسية / المناعة", ku: "هەستیاری / ئیمۆنۆلۆژی" },
  "Animal bite": { ar: "عضة حيوان", ku: "گازگرتنی ئاژەڵ" },
  "Anxiety": { ar: "القلق", ku: "دڵەڕاوکێ" },
  "Back pain": { ar: "ألم الظهر", ku: "ئازاری پشت" },
  "Balance problems": { ar: "مشكلات التوازن", ku: "کێشەی هاوسەنگی" },
  "Blood in stool": { ar: "دم في البراز", ku: "خوێن لە پاشماوە" },
  "Blood in urine": { ar: "دم في البول", ku: "خوێن لە میز" },
  "Blue lips or face": { ar: "ازرقاق الشفاه أو الوجه", ku: "شینبوونی لێو یان ڕووخسار" },
  "Blurred vision": { ar: "تشوش الرؤية", ku: "لێڵبوونی بینین" },
  "Body aches": { ar: "آلام الجسم", ku: "ئازاری جەستە" },
  "Bone pain": { ar: "ألم العظام", ku: "ئازاری ئێسک" },
  "Breast lump": { ar: "كتلة في الثدي", ku: "گرێ لە مەمک" },
  "Burn injury": { ar: "إصابة بحرق", ku: "برینداری سووتان" },
  "Burning urination": { ar: "حرقة أثناء التبول", ku: "سووتان لە کاتی میزکردن" },
  "Cardiac": { ar: "قلبي", ku: "دڵ" },
  "Cardiovascular": { ar: "قلبي وعائي", ku: "دڵ و خوێنبەرەکان" },
  "Chest pain": { ar: "ألم الصدر", ku: "ئازاری سنگ" },
  "Chest tightness": { ar: "ضيق أو انقباض في الصدر", ku: "تەنگی سنگ" },
  "Child breathing difficulty": { ar: "صعوبة التنفس لدى الطفل", ku: "سەختی هەناسەدان لە منداڵ" },
  "Child fever": { ar: "حمى لدى الطفل", ku: "تای منداڵ" },
  "Child rash": { ar: "طفح جلدي لدى الطفل", ku: "پەڵەی پێست لە منداڵ" },
  "Cold intolerance": { ar: "عدم تحمل البرد", ku: "نەگونجان لەگەڵ ساردی" },
  "Constipation": { ar: "الإمساك", ku: "قەبزی" },
  "Cough": { ar: "السعال", ku: "کۆخە" },
  "Coughing blood": { ar: "سعال مصحوب بالدم", ku: "کۆخەکردن بە خوێن" },
  "Cut wound": { ar: "جرح قطعي", ku: "برینی بڕاو" },
  "Dental / Oral": { ar: "الأسنان / الفم", ku: "ددان / دەم" },
  "Dental abscess": { ar: "خراج الأسنان", ku: "خراجی ددان" },
  "Diarrhea": { ar: "الإسهال", ku: "سکچوون" },
  "Difficulty swallowing": { ar: "صعوبة البلع", ku: "سەختی قووتدان" },
  "Digestive": { ar: "هضمي", ku: "هەرس" },
  "Dizziness": { ar: "الدوخة", ku: "سەرگێژە" },
  "Ear pain": { ar: "ألم الأذن", ku: "ئازاری گوێ" },
  "Ear, Nose, and Throat": { ar: "الأذن والأنف والحنجرة", ku: "گۆ، لووت و قوڕگ" },
  "Emergency": { ar: "الطوارئ", ku: "فریاکەوتن" },
  "Emergency / Red Flags": { ar: "الطوارئ / علامات الخطر", ku: "فریاکەوتن / نیشانە مەترسیدارەکان" },
  "Endocrine / Metabolic": { ar: "الغدد الصماء / الأيض", ku: "هۆرمۆنی / میتابۆلیزم" },
  "ENT": { ar: "الأنف والأذن والحنجرة", ku: "گۆ، لووت و قوڕگ" },
  "Erectile dysfunction": { ar: "ضعف الانتصاب", ku: "لاوازیی هەستانی ئەندامی نێرینە" },
  "Excessive sleepiness": { ar: "النعاس المفرط", ku: "خەواڵوویی زۆر" },
  "Excessive thirst": { ar: "العطش المفرط", ku: "تینوێتی زۆر" },
  "Eye": { ar: "العين", ku: "چاو" },
  "Eye discharge": { ar: "إفرازات العين", ku: "دەرهاتنی ماددە لە چاو" },
  "Eye pain": { ar: "ألم العين", ku: "ئازاری چاو" },
  "Eye redness": { ar: "احمرار العين", ku: "سووربوونی چاو" },
  "Facial or lip swelling": { ar: "تورم الوجه أو الشفاه", ku: "ئاوسانی ڕووخسار یان لێو" },
  "Fainting": { ar: "الإغماء", ku: "هۆش لەدەستدان" },
  "Fall injury": { ar: "إصابة نتيجة السقوط", ku: "برینداری بەهۆی کەوتن" },
  "Fatigue": { ar: "الإرهاق", ku: "ماندووبوون" },
  "Fever": { ar: "الحمى", ku: "تا" },
  "Flank pain": { ar: "ألم الخاصرة", ku: "ئازاری لاپاڵ" },
  "Food reaction": { ar: "تفاعل تجاه الطعام", ku: "کاردانەوە بەرامبەر خواردن" },
  "Frequent hunger": { ar: "الجوع المتكرر", ku: "برسیبوونی دووبارە" },
  "Frequent sneezing": { ar: "العطاس المتكرر", ku: "پژمینەوەی زۆر" },
  "Frequent urination": { ar: "كثرة التبول", ku: "میزکردنی زۆر" },
  "Frequent urination with thirst": { ar: "كثرة التبول مع العطش", ku: "میزکردنی زۆر لەگەڵ تینوێتی" },
  "Gastrointestinal": { ar: "الجهاز الهضمي", ku: "گەدە و ڕیخۆڵەکان" },
  "General": { ar: "عام", ku: "گشتی" },
  "General / Constitutional": { ar: "عام / أعراض جهازية", ku: "گشتی / نیشانەکانی تەواوی جەستە" },
  "General weakness": { ar: "ضعف عام", ku: "لاوازی گشتی" },
  "Gum swelling": { ar: "تورم اللثة", ku: "ئاوسانی پووک" },
  "Hair loss": { ar: "تساقط الشعر", ku: "ڕژانی قژ" },
  "Head injury": { ar: "إصابة في الرأس", ku: "برینداری سەر" },
  "Headache": { ar: "الصداع", ku: "سەرئێشە" },
  "Hearing loss": { ar: "فقدان السمع", ku: "لەدەستدانی بیستن" },
  "Heartburn": { ar: "حرقة المعدة", ku: "سووتانی گەدە" },
  "Heat intolerance": { ar: "عدم تحمل الحرارة", ku: "نەگونجان لەگەڵ گەرمی" },
  "High blood pressure reading": { ar: "قراءة مرتفعة لضغط الدم", ku: "خوێندنەوەی بەرزی پەستانی خوێن" },
  "Hives": { ar: "الشرى", ku: "هەڵدانەوەی هەستیاری پێست" },
  "Hoarseness": { ar: "بحة الصوت", ku: "گرژبوونی دەنگ" },
  "Injury / Trauma": { ar: "الإصابات / الرضوض", ku: "برینداری / تروما" },
  "Insomnia": { ar: "الأرق", ku: "بێخەوی" },
  "Irritability": { ar: "سرعة الانفعال", ku: "تووڕەبوونی ئاسان" },
  "Itching": { ar: "الحكة", ku: "خوران" },
  "Itchy eyes": { ar: "حكة العينين", ku: "خورانی چاو" },
  "Jaundice": { ar: "اليرقان", ku: "زەردبوون" },
  "Jaw pain": { ar: "ألم الفك", ku: "ئازاری چەناگە" },
  "Joint pain": { ar: "ألم المفصل", ku: "ئازاری جومگە" },
  "Leg swelling": { ar: "تورم الساق", ku: "ئاوسانی قاچ" },
  "Light sensitivity": { ar: "حساسية للضوء", ku: "هەستیاری بەرامبەر ڕووناکی" },
  "Limited movement": { ar: "محدودية الحركة", ku: "سنورداری جووڵە" },
  "Loss of appetite": { ar: "فقدان الشهية", ku: "لەدەستدانی ئارەزووی خواردن" },
  "Loss of consciousness": { ar: "فقدان الوعي", ku: "لەدەستدانی هۆشیاری" },
  "Low mood": { ar: "انخفاض المزاج", ku: "دابەزینی باری دەروونی" },
  "Medication reaction": { ar: "تفاعل تجاه دواء", ku: "کاردانەوە بەرامبەر دەرمان" },
  "Memory problems": { ar: "مشكلات الذاكرة", ku: "کێشەی بیرەوەری" },
  "Mental Health": { ar: "الصحة النفسية", ku: "تەندروستی دەروونی" },
  "Mental Health / Sleep": { ar: "الصحة النفسية / النوم", ku: "تەندروستی دەروونی / خەو" },
  "Migraine-like headache": { ar: "صداع شبيه بالشقيقة", ku: "سەرئێشەی وەک Migraine" },
  "Mole or lesion change": { ar: "تغير في شامة أو آفة جلدية", ku: "گۆڕانی خاڵ یان زامی پێست" },
  "Mouth ulcer": { ar: "قرحة فموية", ku: "برینی دەم" },
  "Muscle pain": { ar: "ألم العضلات", ku: "ئازاری ماسولکە" },
  "Muscle weakness": { ar: "ضعف العضلات", ku: "لاوازی ماسولکە" },
  "Musculoskeletal": { ar: "عضلي هيكلي", ku: "ماسولکە و ئێسک" },
  "Nasal congestion": { ar: "احتقان الأنف", ku: "گیرانی لووت" },
  "Nausea": { ar: "الغثيان", ku: "هەست بە دڵتێکەڵبوون" },
  "Neck pain": { ar: "ألم الرقبة", ku: "ئازاری مل" },
  "Neurological": { ar: "عصبي", ku: "دەمار" },
  "Night sweats": { ar: "تعرق ليلي", ku: "ئارەقەکردنی شەوانە" },
  "Nosebleed": { ar: "نزيف الأنف", ku: "خوێنبەربوونی لووت" },
  "Numbness or tingling": { ar: "خدر أو تنميل", ku: "بێهەستی یان مێروولەکردن" },
  "P5A chest adee0724": { ar: "P5A chest adee0724", ku: "P5A chest adee0724" },
  "P5A-adee0724": { ar: "P5A-adee0724", ku: "P5A-adee0724" },
  "Painful urination": { ar: "ألم أثناء التبول", ku: "ئازار لە کاتی میزکردن" },
  "Palpitations": { ar: "خفقان القلب", ku: "لێدانی هەستپێکراوی دڵ" },
  "Panic attacks": { ar: "نوبات الهلع", ku: "هێرشەکانی ترس" },
  "Pediatric Concerns": { ar: "مشكلات الأطفال", ku: "کێشەکانی منداڵان" },
  "Pelvic pain": { ar: "ألم الحوض", ku: "ئازاری حەوز" },
  "Persistent crying in infant": { ar: "بكاء مستمر لدى الرضيع", ku: "گریانی بەردەوام لە ساوا" },
  "Phase5A chest 0a13e40e": { ar: "Phase5A chest 0a13e40e", ku: "Phase5A chest 0a13e40e" },
  "Phase5A-0a13e40e": { ar: "Phase5A-0a13e40e", ku: "Phase5A-0a13e40e" },
  "Poor feeding in infant": { ar: "ضعف الرضاعة لدى الرضيع", ku: "خۆراک/شیرخواردنی لاواز لە ساوا" },
  "Pregnancy concern": { ar: "مشكلة أو قلق متعلق بالحمل", ku: "نیگەرانی پەیوەندیدار بە دووگیانی" },
  "Racing heart": { ar: "تسارع ضربات القلب", ku: "خێرایی لێدانی دڵ" },
  "Reduced urination": { ar: "قلة التبول", ku: "کەمبوونی میزکردن" },
  "Reproductive / Gynecology": { ar: "التناسلي / أمراض النساء", ku: "زاوزێ / نەخۆشییەکانی ژنان" },
  "Respiratory": { ar: "تنفسي", ku: "هەناسەدان" },
  "Runny nose": { ar: "سيلان الأنف", ku: "ڕژانی لووت" },
  "Seizure": { ar: "نوبة صرع", ku: "سەرع" },
  "Severe abdominal pain": { ar: "ألم بطني شديد", ku: "ئازاری زۆری سک" },
  "Severe allergic reaction": { ar: "تفاعل تحسسي شديد", ku: "کاردانەوەی هەستیاریی توند" },
  "Severe bleeding": { ar: "نزيف شديد", ku: "خوێنبەربوونی زۆر" },
  "Severe chest pain": { ar: "ألم صدري شديد", ku: "ئازاری زۆری سنگ" },
  "Severe shortness of breath": { ar: "ضيق نفس شديد", ku: "تەنگەنەفەسیی زۆر" },
  "Shortness of breath": { ar: "ضيق النفس", ku: "تەنگەنەفەسی" },
  "Signs of dehydration in child": { ar: "علامات الجفاف لدى الطفل", ku: "نیشانەکانی وشکبوونەوە لە منداڵ" },
  "Sinus pain": { ar: "ألم الجيوب الأنفية", ku: "ئازاری Sinus" },
  "Skin": { ar: "جلدي", ku: "پێست" },
  "Skin / Dermatology": { ar: "الجلد / الأمراض الجلدية", ku: "پێست / پزیشکی پێست" },
  "Skin discoloration": { ar: "تغير لون الجلد", ku: "گۆڕانی ڕەنگی پێست" },
  "Skin infection": { ar: "عدوى جلدية", ku: "هەوکردنی پێست" },
  "Skin rash": { ar: "طفح جلدي", ku: "پەڵەی پێست" },
  "Skin wound": { ar: "جرح جلدي", ku: "برینی پێست" },
  "Sore throat": { ar: "التهاب أو ألم الحلق", ku: "ئازاری قوڕگ" },
  "Speech difficulty": { ar: "صعوبة الكلام", ku: "سەختی قسەکردن" },
  "Sprain or strain": { ar: "التواء أو شد عضلي", ku: "پێچانەوە یان کشانی ماسولکە" },
  "Sudden confusion": { ar: "ارتباك مفاجئ", ku: "تێکچوونی هۆشیاریی لەناکاو" },
  "Sudden severe headache": { ar: "صداع شديد مفاجئ", ku: "سەرئێشەی زۆری لەناکاو" },
  "Sudden weakness on one side": { ar: "ضعف مفاجئ في جهة واحدة", ku: "لاوازیی لەناکاو لە یەک لای جەستە" },
  "Suicidal thoughts": { ar: "أفكار انتحارية", ku: "بیرکردنەوە لە خۆکوشتن" },
  "Suspected fracture": { ar: "اشتباه بوجود كسر", ku: "گومانی شکان" },
  "Swelling at joint": { ar: "تورم في المفصل", ku: "ئاوسان لە جومگە" },
  "Testicular pain": { ar: "ألم الخصية", ku: "ئازاری هێلکەدان" },
  "Tinnitus": { ar: "طنين الأذن", ku: "دەنگدانەوە لە گوێ" },
  "Tooth pain": { ar: "ألم الأسنان", ku: "ئازاری ددان" },
  "Tremor": { ar: "الرعاش", ku: "لەرزە" },
  "Unexplained weight gain": { ar: "زيادة وزن غير مفسرة", ku: "زیادبوونی کێش بەبێ هۆکاری ڕوون" },
  "Unexplained weight loss": { ar: "نقصان وزن غير مفسر", ku: "کەمبوونی کێش بەبێ هۆکاری ڕوون" },
  "Urinary": { ar: "بولي", ku: "میز" },
  "Urinary / Kidney": { ar: "البولي / الكلى", ku: "میز / گورچیلە" },
  "Urinary leakage": { ar: "سلس البول", ku: "دەرچوونی بێویستی میز" },
  "Vaginal discharge": { ar: "إفرازات مهبلية", ku: "دەرهاتنی ماددە لە زێ" },
  "Vision loss": { ar: "فقدان البصر", ku: "لەدەستدانی بینین" },
  "Vomiting": { ar: "القيء", ku: "ڕشانەوە" },
  "Weight loss": { ar: "نقصان الوزن", ku: "کەمبوونی کێش" },
  "Wheezing": { ar: "الأزيز التنفسي", ku: "ویزەی هەناسە" },
  "Women's Health": { ar: "صحة المرأة", ku: "تەندروستی ئافرەتان" },
};
